<?php

error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);



function maestro_createtestworkflow() {
	echo "step 1";
include('maestro.admin.inc');
echo "step 2";
$_POST['offset_top'] = 0;
$_POST['offset_left'] = 0;
$variable_xref_array = Array();
$variable_xref_array[0] = 0;
$task_xref_array = Array();
$task_xref_array[0] = 0;
$templateID = maestro_createNewTemplate("IMPORT - Blaine's Test", TRUE, TRUE);
$variable_xref_array[3] = maestro_createTemplateVariable($templateID, "initiator", "");
$variable_xref_array[4] = maestro_createTemplateVariable($templateID, "content_type", "article");
$ti = new MaestroTaskInterfaceStart(0, $templateID);
$ti->create();
$task_xref_array[7] = $ti->get_task_id();
$res = db_select('maestro_template_data', 'a');
$res->fields('a', array('id', 'task_data'));
$res->condition('a.id', $ti->get_task_id(), '=');
$rec = current($res->execute()->fetchAll());
$rec->is_interactive = 0;
$fixed_data = $ti->modulateExportTaskData('', $variable_xref_array);
$rec->task_data = $fixed_data;
$rec->handler = '';
$rec->first_task = 1;
$rec->taskname = 'Start';
$rec->assigned_by_variable = 0;
$rec->argument_variable = '';
$rec->regenerate = 0;
$rec->regen_all_live_tasks = 0;
$rec->is_dynamic_taskname = 0;
$rec->dynamic_taskname_variable_id = 0;
$rec->reminder_interval = 0;
$rec->reminder_interval_variable = 0;
$rec->subsequent_reminder_interval = 0;
$rec->last_updated = 0;
$rec->pre_notify_subject = '';
$rec->post_notify_subject = '';
$rec->reminder_subject = '';
$rec->pre_notify_message = '';
$rec->post_notify_message = '';
$rec->reminder_message = '';
$rec->num_reminders = 0;
$rec->escalate_variable_id = 0;
$rec->offset_left = 93;
$rec->offset_top = 158;
$rec->surpress_first_notification = 0;
drupal_write_record('maestro_template_data', $rec, array('id'));
$ti = new MaestroTaskInterfaceEnd(0, $templateID);
$ti->create();
$task_xref_array[8] = $ti->get_task_id();
$res = db_select('maestro_template_data', 'a');
$res->fields('a', array('id', 'task_data'));
$res->condition('a.id', $ti->get_task_id(), '=');
$rec = current($res->execute()->fetchAll());
$rec->is_interactive = 0;
$fixed_data = $ti->modulateExportTaskData('', $variable_xref_array);
$rec->task_data = $fixed_data;
$rec->handler = '';
$rec->first_task = 0;
$rec->taskname = 'End';
$rec->assigned_by_variable = 0;
$rec->argument_variable = '';
$rec->regenerate = 0;
$rec->regen_all_live_tasks = 0;
$rec->is_dynamic_taskname = 0;
$rec->dynamic_taskname_variable_id = 0;
$rec->reminder_interval = 0;
$rec->reminder_interval_variable = 0;
$rec->subsequent_reminder_interval = 0;
$rec->last_updated = 0;
$rec->pre_notify_subject = '';
$rec->post_notify_subject = '';
$rec->reminder_subject = '';
$rec->pre_notify_message = '';
$rec->post_notify_message = '';
$rec->reminder_message = '';
$rec->num_reminders = 0;
$rec->escalate_variable_id = 0;
$rec->offset_left = 917;
$rec->offset_top = 458;
$rec->surpress_first_notification = 0;
drupal_write_record('maestro_template_data', $rec, array('id'));
$ti = new MaestroTaskInterfaceContentType(0, $templateID);
$ti->create();
$task_xref_array[9] = $ti->get_task_id();
$res = db_select('maestro_template_data', 'a');
$res->fields('a', array('id', 'task_data'));
$res->condition('a.id', $ti->get_task_id(), '=');
$rec = current($res->execute()->fetchAll());
$rec->is_interactive = 1;
$fixed_data = $ti->modulateExportTaskData('a:1:{s:12:"content_type";s:7:"article";}', $variable_xref_array);
$rec->task_data = $fixed_data;
$rec->handler = '';
$rec->first_task = 0;
$rec->taskname = 'Create New Article';
$rec->assigned_by_variable = 1;
$rec->argument_variable = '';
$rec->regenerate = 1;
$rec->regen_all_live_tasks = 0;
$rec->is_dynamic_taskname = 0;
$rec->dynamic_taskname_variable_id = 0;
$rec->reminder_interval = 0;
$rec->reminder_interval_variable = 0;
$rec->subsequent_reminder_interval = 0;
$rec->last_updated = 0;
$rec->pre_notify_subject = '';
$rec->post_notify_subject = '';
$rec->reminder_subject = '';
$rec->pre_notify_message = '';
$rec->post_notify_message = '';
$rec->reminder_message = '';
$rec->num_reminders = 0;
$rec->escalate_variable_id = 0;
$rec->offset_left = 273;
$rec->offset_top = 158;
$rec->surpress_first_notification = 0;
drupal_write_record('maestro_template_data', $rec, array('id'));
$ti = new MaestroTaskInterfaceInteractiveFunction(0, $templateID);
$ti->create();
$task_xref_array[10] = $ti->get_task_id();
$res = db_select('maestro_template_data', 'a');
$res->fields('a', array('id', 'task_data'));
$res->condition('a.id', $ti->get_task_id(), '=');
$rec = current($res->execute()->fetchAll());
$rec->is_interactive = 1;
$fixed_data = $ti->modulateExportTaskData('a:2:{s:7:"handler";s:25:"maestro_reviewContentType";s:13:"optional_parm";a:1:{s:12:"content_type";s:7:"article";}}', $variable_xref_array);
$rec->task_data = $fixed_data;
$rec->handler = '';
$rec->first_task = 0;
$rec->taskname = 'Editor Review Article';
$rec->assigned_by_variable = 0;
$rec->argument_variable = '';
$rec->regenerate = 1;
$rec->regen_all_live_tasks = 0;
$rec->is_dynamic_taskname = 0;
$rec->dynamic_taskname_variable_id = 0;
$rec->reminder_interval = 0;
$rec->reminder_interval_variable = 0;
$rec->subsequent_reminder_interval = 0;
$rec->last_updated = 0;
$rec->pre_notify_subject = '';
$rec->post_notify_subject = '';
$rec->reminder_subject = '';
$rec->pre_notify_message = '';
$rec->post_notify_message = '';
$rec->reminder_message = '';
$rec->num_reminders = 0;
$rec->escalate_variable_id = 0;
$rec->offset_left = 478;
$rec->offset_top = 153;
$rec->surpress_first_notification = 0;
drupal_write_record('maestro_template_data', $rec, array('id'));
$ti = new MaestroTaskInterfaceIf(0, $templateID);
$ti->create();
$task_xref_array[11] = $ti->get_task_id();
$res = db_select('maestro_template_data', 'a');
$res->fields('a', array('id', 'task_data'));
$res->condition('a.id', $ti->get_task_id(), '=');
$rec = current($res->execute()->fetchAll());
$rec->is_interactive = 0;
$fixed_data = $ti->modulateExportTaskData('a:5:{s:11:"if_operator";s:0:"";s:8:"if_value";s:0:"";s:20:"if_process_arguments";s:15:"lasttasksuccess";s:20:"if_argument_variable";s:0:"";s:17:"if_task_arguments";s:6:"status";}', $variable_xref_array);
$rec->task_data = $fixed_data;
$rec->handler = '';
$rec->first_task = 0;
$rec->taskname = 'Check if Editor Accepted';
$rec->assigned_by_variable = 0;
$rec->argument_variable = '';
$rec->regenerate = 0;
$rec->regen_all_live_tasks = 0;
$rec->is_dynamic_taskname = 0;
$rec->dynamic_taskname_variable_id = 0;
$rec->reminder_interval = 0;
$rec->reminder_interval_variable = 0;
$rec->subsequent_reminder_interval = 0;
$rec->last_updated = 0;
$rec->pre_notify_subject = '';
$rec->post_notify_subject = '';
$rec->reminder_subject = '';
$rec->pre_notify_message = '';
$rec->post_notify_message = '';
$rec->reminder_message = '';
$rec->num_reminders = 0;
$rec->escalate_variable_id = 0;
$rec->offset_left = 442;
$rec->offset_top = 281;
$rec->surpress_first_notification = 0;
drupal_write_record('maestro_template_data', $rec, array('id'));
$ti = new MaestroTaskInterfaceInteractiveFunction(0, $templateID);
$ti->create();
$task_xref_array[12] = $ti->get_task_id();
$res = db_select('maestro_template_data', 'a');
$res->fields('a', array('id', 'task_data'));
$res->condition('a.id', $ti->get_task_id(), '=');
$rec = current($res->execute()->fetchAll());
$rec->is_interactive = 1;
$fixed_data = $ti->modulateExportTaskData('a:2:{s:7:"handler";s:25:"maestro_reviewContentType";s:13:"optional_parm";a:1:{s:12:"content_type";s:7:"article";}}', $variable_xref_array);
$rec->task_data = $fixed_data;
$rec->handler = '';
$rec->first_task = 0;
$rec->taskname = 'New Task';
$rec->assigned_by_variable = 0;
$rec->argument_variable = '';
$rec->regenerate = 0;
$rec->regen_all_live_tasks = 0;
$rec->is_dynamic_taskname = 0;
$rec->dynamic_taskname_variable_id = 0;
$rec->reminder_interval = 0;
$rec->reminder_interval_variable = 0;
$rec->subsequent_reminder_interval = 0;
$rec->last_updated = 0;
$rec->pre_notify_subject = '';
$rec->post_notify_subject = '';
$rec->reminder_subject = '';
$rec->pre_notify_message = '';
$rec->post_notify_message = '';
$rec->reminder_message = '';
$rec->num_reminders = 0;
$rec->escalate_variable_id = 0;
$rec->offset_left = 443;
$rec->offset_top = 363;
$rec->surpress_first_notification = 0;
drupal_write_record('maestro_template_data', $rec, array('id'));
$ti = new MaestroTaskInterfaceIf(0, $templateID);
$ti->create();
$task_xref_array[13] = $ti->get_task_id();
$res = db_select('maestro_template_data', 'a');
$res->fields('a', array('id', 'task_data'));
$res->condition('a.id', $ti->get_task_id(), '=');
$rec = current($res->execute()->fetchAll());
$rec->is_interactive = 0;
$fixed_data = $ti->modulateExportTaskData('a:5:{s:11:"if_operator";s:0:"";s:8:"if_value";s:0:"";s:20:"if_process_arguments";s:15:"lasttasksuccess";s:20:"if_argument_variable";s:0:"";s:17:"if_task_arguments";s:6:"status";}', $variable_xref_array);
$rec->task_data = $fixed_data;
$rec->handler = '';
$rec->first_task = 0;
$rec->taskname = 'Check if Publisher Accepted';
$rec->assigned_by_variable = 0;
$rec->argument_variable = '';
$rec->regenerate = 0;
$rec->regen_all_live_tasks = 0;
$rec->is_dynamic_taskname = 0;
$rec->dynamic_taskname_variable_id = 0;
$rec->reminder_interval = 0;
$rec->reminder_interval_variable = 0;
$rec->subsequent_reminder_interval = 0;
$rec->last_updated = 0;
$rec->pre_notify_subject = '';
$rec->post_notify_subject = '';
$rec->reminder_subject = '';
$rec->pre_notify_message = '';
$rec->post_notify_message = '';
$rec->reminder_message = '';
$rec->num_reminders = 0;
$rec->escalate_variable_id = 0;
$rec->offset_left = 692;
$rec->offset_top = 373;
$rec->surpress_first_notification = 0;
drupal_write_record('maestro_template_data', $rec, array('id'));
$ti = new MaestroTaskInterfaceBatchFunction(0, $templateID);
$ti->create();
$task_xref_array[14] = $ti->get_task_id();
$res = db_select('maestro_template_data', 'a');
$res->fields('a', array('id', 'task_data'));
$res->condition('a.id', $ti->get_task_id(), '=');
$rec = current($res->execute()->fetchAll());
$rec->is_interactive = 0;
$fixed_data = $ti->modulateExportTaskData('a:2:{s:7:"handler";s:22:"maestro_publishArticle";s:13:"optional_parm";a:0:{}}', $variable_xref_array);
$rec->task_data = $fixed_data;
$rec->handler = '';
$rec->first_task = 0;
$rec->taskname = 'Publish Article';
$rec->assigned_by_variable = 0;
$rec->argument_variable = '';
$rec->regenerate = 0;
$rec->regen_all_live_tasks = 0;
$rec->is_dynamic_taskname = 0;
$rec->dynamic_taskname_variable_id = 0;
$rec->reminder_interval = 0;
$rec->reminder_interval_variable = 0;
$rec->subsequent_reminder_interval = 0;
$rec->last_updated = 0;
$rec->pre_notify_subject = '';
$rec->post_notify_subject = '';
$rec->reminder_subject = '';
$rec->pre_notify_message = '';
$rec->post_notify_message = '';
$rec->reminder_message = '';
$rec->num_reminders = 0;
$rec->escalate_variable_id = 0;
$rec->offset_left = 719;
$rec->offset_top = 455;
$rec->surpress_first_notification = 0;
drupal_write_record('maestro_template_data', $rec, array('id'));
$sql = "INSERT INTO {maestro_template_data_next_step} (template_data_from, template_data_to, template_data_to_false) VALUES (:a1, :b1, :c1)";
db_query($sql, array('a1' => $task_xref_array[7], 'b1' => $task_xref_array[9], 'c1' => $task_xref_array[0]));
$sql = "INSERT INTO {maestro_template_data_next_step} (template_data_from, template_data_to, template_data_to_false) VALUES (:a1, :b1, :c1)";
db_query($sql, array('a1' => $task_xref_array[9], 'b1' => $task_xref_array[10], 'c1' => $task_xref_array[0]));
$query = db_select('maestro_template_data', 'a');
$query->fields('a',array('task_class_name'));
$query->condition('a.id',$task_xref_array[9],'=');
$name=current($query->execute()->fetchAll());
$task_type = substr($name->task_class_name, 15);
$task_class = 'MaestroTaskInterface' . $task_type;
$ti = new $task_class(0,0);
$modulated_user = $ti->modulateExportUser("");
$sql = "INSERT INTO {maestro_template_assignment} (template_data_id, uid, gid, process_variable, pre_notify_variable, post_notify_variable, reminder_notify_variable) VALUES (:a1, :b1, :c1, :d1, :e1, :f1, :g1)";
db_query($sql, array( 'a1' => $task_xref_array[9],'b1' => $modulated_user,'c1' => 0,'d1' => $variable_xref_array[3],'e1' => 0,'f1' => 0,'g1' => 0));
$sql = "INSERT INTO {maestro_template_data_next_step} (template_data_from, template_data_to, template_data_to_false) VALUES (:a1, :b1, :c1)";
db_query($sql, array('a1' => $task_xref_array[10], 'b1' => $task_xref_array[11], 'c1' => $task_xref_array[0]));
$query = db_select('maestro_template_data', 'a');
$query->fields('a',array('task_class_name'));
$query->condition('a.id',$task_xref_array[10],'=');
$name=current($query->execute()->fetchAll());
$task_type = substr($name->task_class_name, 15);
$task_class = 'MaestroTaskInterface' . $task_type;
$ti = new $task_class(0,0);
$modulated_user = $ti->modulateExportUser("Editor");
$sql = "INSERT INTO {maestro_template_assignment} (template_data_id, uid, gid, process_variable, pre_notify_variable, post_notify_variable, reminder_notify_variable) VALUES (:a1, :b1, :c1, :d1, :e1, :f1, :g1)";
db_query($sql, array( 'a1' => $task_xref_array[10],'b1' => $modulated_user,'c1' => 0,'d1' => $variable_xref_array[0],'e1' => 0,'f1' => 0,'g1' => 0));
$sql = "INSERT INTO {maestro_template_data_next_step} (template_data_from, template_data_to, template_data_to_false) VALUES (:a1, :b1, :c1)";
db_query($sql, array('a1' => $task_xref_array[11], 'b1' => $task_xref_array[0], 'c1' => $task_xref_array[9]));
$sql = "INSERT INTO {maestro_template_data_next_step} (template_data_from, template_data_to, template_data_to_false) VALUES (:a1, :b1, :c1)";
db_query($sql, array('a1' => $task_xref_array[11], 'b1' => $task_xref_array[12], 'c1' => $task_xref_array[0]));
$sql = "INSERT INTO {maestro_template_data_next_step} (template_data_from, template_data_to, template_data_to_false) VALUES (:a1, :b1, :c1)";
db_query($sql, array('a1' => $task_xref_array[12], 'b1' => $task_xref_array[13], 'c1' => $task_xref_array[0]));
$query = db_select('maestro_template_data', 'a');
$query->fields('a',array('task_class_name'));
$query->condition('a.id',$task_xref_array[12],'=');
$name=current($query->execute()->fetchAll());
$task_type = substr($name->task_class_name, 15);
$task_class = 'MaestroTaskInterface' . $task_type;
$ti = new $task_class(0,0);
$modulated_user = $ti->modulateExportUser("Publisher");
$sql = "INSERT INTO {maestro_template_assignment} (template_data_id, uid, gid, process_variable, pre_notify_variable, post_notify_variable, reminder_notify_variable) VALUES (:a1, :b1, :c1, :d1, :e1, :f1, :g1)";
db_query($sql, array( 'a1' => $task_xref_array[12],'b1' => $modulated_user,'c1' => 0,'d1' => $variable_xref_array[0],'e1' => 0,'f1' => 0,'g1' => 0));
$sql = "INSERT INTO {maestro_template_data_next_step} (template_data_from, template_data_to, template_data_to_false) VALUES (:a1, :b1, :c1)";
db_query($sql, array('a1' => $task_xref_array[13], 'b1' => $task_xref_array[0], 'c1' => $task_xref_array[10]));
$sql = "INSERT INTO {maestro_template_data_next_step} (template_data_from, template_data_to, template_data_to_false) VALUES (:a1, :b1, :c1)";
db_query($sql, array('a1' => $task_xref_array[13], 'b1' => $task_xref_array[14], 'c1' => $task_xref_array[0]));
$sql = "INSERT INTO {maestro_template_data_next_step} (template_data_from, template_data_to, template_data_to_false) VALUES (:a1, :b1, :c1)";
db_query($sql, array('a1' => $task_xref_array[14], 'b1' => $task_xref_array[8], 'c1' => $task_xref_array[0]));

}