<?php
// $Id:

/**
 * @file
 * maestro__common.module
 */

/* Maestro HOOK to modules to return info on any new task handlers - ie functions for tasks */
function maestro_common_maestro_handler_options() {

  $handlers = array(
    'MaestroTaskTypeInteractiveFunction' => array(
      'maestro_show_message' => t('Generic Function to display a message. Requires that you use a process variables called "message" that is set to the message string you want displayed.'),
      'maestro_accept_reject' => t('Simple Accept/reject function that lets you set a "message" var for the output and shows a simple accept/reject button.'),
      )
    );
    return $handlers;
}


function maestro_show_message($op,&$task,$parms) {
  global $base_url;

  $retval = new stdClass();
  $retval->html = '';
  $retval->retcode = FALSE;
  $retval->engineop = '';

  switch ($op) {
    case 'display':
      if (!isset($parms['message'])) {
        $maestro = Maestro::createMaestroObject(1);
        $parms['message'] = $maestro->engine()->getProcessVariable('message', $task->_properties->process_id);
      }
      $retval->html = drupal_render(drupal_get_form('maestro_show_message_form',array('message' => $parms['message'])));
      $retval->retcode = TRUE;
      $retval->engineop = '';
      break;
    case 'complete':
      $retval->retcode = TRUE;
      $retval->engineop = 'completetask';
      break;
  }

  return $retval;

}

function maestro_show_message_form($form, $form_state, $parms) {

  $form = array();
  $form['message'] = array(
    '#prefix' => '<div class="maestro_interactive_task_message">',
    '#suffix' => '</div>',
    '#markup' =>  $parms['message'],
  );

  $form['actions']['complete_task'] = array(
    '#type' => 'button',
    '#default_value' => t('Complete Task'),
    '#attributes' => array('maestro' => array('complete')),
  );

  return $form;

}


/* Batch function - dummy or test function returns TRUE */
function maestro_batch_dummy($queue_id, $process_id) {
  return TRUE;
}


/*
 * Implementation of a Maestro interactive function handler
 * This one handles a simple output of an Accept/Reject task with the ability to set the message to whatever the user likes.
 */
function maestro_accept_reject($op,&$task,$parms) {
  global $base_url;

  $retval = new stdClass();
  $retval->html = '';
  $retval->retcode = FALSE;
  $retval->engineop = '';

  switch ($op) {
    case 'display':
      if (!isset($parms['message'])) {
        $maestro = Maestro::createMaestroObject(1);
        $parms['message'] = $maestro->engine()->getProcessVariable('message', $task->_properties->process_id);
      }
      $retval->html = drupal_render(drupal_get_form('maestro_show_message_accept_reject_form',array('message' => $parms['message'])));
      $retval->retcode = TRUE;
      $retval->engineop = '';
      break;
    case 'accept':
      $retval->retcode = TRUE;
      $retval->engineop = 'completetask';
      break;
    case 'reject':
      $retval->status = MaestroProjectStatusCodes::STATUS_CANCELLED;
      $retval->retcode = TRUE;
      $retval->engineop = 'completetask';
      break;
  }
  return $retval;
}

function maestro_show_message_accept_reject_form($form, $form_state, $parms) {

  $form = array();
  $form['message'] = array(
    '#prefix' => '<div class="maestro_interactive_task_message">',
    '#suffix' => '</div>',
    '#markup' =>  $parms['message'],
  );

  $form['actions']['complete_task'] = array(
    '#type' => 'button',
    '#default_value' => t('Accept'),
    '#attributes' => array('maestro' => array('accept')),
  );
  $form['actions']['update_task'] = array(
    '#type' => 'button',
    '#default_value' => t('Reject'),
    '#attributes' => array('maestro' => array('reject')),
  );

  return $form;

}
