<?php
// $Id:

/**
 * @file
 * myfunctions.php
 */


function maestro_content_publish_theme() {
  return array(
    'maestro_content_publish_review' => array(
      'template' => 'content_review',
      'variables' => array('nid' => NULL, 'queue_id' => NULL, 'title' => NULL, 'data' => NULL),
    )
  );
}


function template_preprocess_maestro_content_publish_review(&$variables) {
  global $base_url;
  $variables['edit_content_link'] = $base_url.'/node/'.$variables['nid'].'/edit/maestro/edit/'. $variables['queue_id'];
  $variables['radio1opt'] = '';
  $variables['radio2opt'] = '';
  if ($variables['data']['reviewstatus'] == 'accept') {
    $variables['radio2opt'] = 'CHECKED=checked';
  } elseif ($variables['data']['reviewstatus'] == 'reject') {
    $variables['radio1opt'] = 'CHECKED=checked';
  }
}

function maestro_showmessage($op,&$task,$parms) {
  global $base_url;

  $retval = new stdClass();
  $retval->html = '';
  $retval->retcode = FALSE;
  $retval->engineop = '';

  switch ($op) {
    case 'display':
      $retval->html = '<div style="text-align:center;margin:5px;padding:10px;border:1px solid #CCC;font-size:14pt;">';
      $retval->html .= $parms['message'];
      $retval->html .= '<div style="float:right;padding-right;">';
      $retval->html .= '<form style="margin:0px;">';
      $retval->html .= '<div style="font-size:10pt;"><input maestro="complete" type="button" value="Complete Task"></div>';
      $retval->html .= '</form>';
      $retval->html .= '</div>';
      $retval->retcode = TRUE;
      $retval->engineop = '';
      break;
    case 'complete':
      $retval->retcode = TRUE;
      $retval->engineop = 'completetask';
      break;
  }

  return $retval;

}


function maestro_basicformtest($op,&$task,$parms) {
  global $base_url;

  $retval = new stdClass();
  $retval->html = '';
  $retval->retcode = FALSE;
  $retval->engineop = '';  // Optionally set the engineop value if you want to complete the task

  switch ($op) {
    case 'display':
      $data = $task->getTempData();
      $retval->html = '<div style="margin:5px;padding:10px;border:1px solid #CCC;">';
      $retval->html .= '<form style="margin:0px;">';
      $retval->html .= '<div style="float:left;width:75%;">';
      $retval->html .= '<div>This is a basic form test which would display some message here</div>';
      $retval->html .= '<p><label>What is your name: </label><input type="text" name="name" value="'.$data['name'] .'"></p>';
      $retval->html .= '<p><label>What is your company name: </label><input type="text" name="company" value="'.$data['company'] .'"></p>';
      $retval->html .= '</div>';
      $retval->html .= '<div style="float:right;width:25%;white-space:nowrap">';
      $retval->html .= '<span style="float:right;"><input maestro="complete" type="button" value="Complete Task"></span>';
      $retval->html .= '<span style="float:right;"><input maestro="save" type="button" value="Save"></span>';
      $retval->html .= '</div>';
      $retval->html .= '</form>';
      $retval->html .= '<div style="clear:both;"></div>';
      $retval->html .= '</div>';
      $retval->retcode = TRUE;
      $retval->engineop = '';
      break;
    case 'complete':
      $retval->retcode = TRUE;
      $retval->engineop = 'completetask';
      break;
    case 'save':
      $data['name'] = $_POST['name'];
      $data['company'] = $_POST['company'];
      $task->saveTempData($data);
      $retval->retcode = TRUE;
      break;
  }

  return $retval;

}


function maestro_reviewContentType($op,&$task,$parms) {
  global $base_url;

  $nid = maestro_getNodeId($task->_properties->process_id,$parms['content_type']);

  if ($nid === FALSE) {
    $retval->retcode = FALSE;
    return $retval;
  }

  $node = node_load($nid);
  if ($node === FALSE) {
    $retval->retcode = FALSE;
    return $retval;
  }
  $retval = new stdClass();
  $retval->html = '';
  $retval->retcode = FALSE;
  $retval->engineop = '';  // Optionally set the engineop value if you want to complete the task

  switch ($op) {
    case 'display':
      $data = $task->getTempData();
      $retval->html = theme('maestro_content_publish_review',array(
        'nid' => $nid,
        'queue_id' => $task->_properties->queue_id,
        'title' => $node->title,
        'data' => $data));

      $retval->retcode = TRUE;
      $retval->engineop = '';
      break;
    case 'complete':
      $data = $task->getTempData();
      if (empty($data['reviewstatus']) AND !isset($_POST['reviewstatus'])) {
        $retval->retcode = FALSE;
      } elseif ($data['reviewstatus'] == 'accept' OR $_POST['reviewstatus'] == 'yes') {
        $data['reviewstatus'] = 'accept';
        $task->saveTempData($data);
        $retval->retcode = TRUE;
        $retval->status = MaestroTaskStatusCodes::STATUS_COMPLETE;
        $retval->engineop = 'completetask';
      } elseif ($data['reviewstatus'] == 'reject' OR $_POST['reviewstatus'] == 'no') {
        $data['reviewstatus'] = 'reject';
        $task->saveTempData($data);
        $retval->retcode = TRUE;
        $retval->status = MaestroTaskStatusCodes::STATUS_IF_CONDITION_FALSE;
        $retval->engineop = 'completetask';
      } else {
        $retval->retcode = FALSE;
      }
      break;
    case 'update':
      if($_POST['reviewstatus'] == 'yes') {
        $data['reviewstatus'] = 'accept';
        $task->saveTempData($data);
      } elseif ($_POST['reviewstatus'] == 'no') {
        $data['reviewstatus'] = 'reject';
        $task->saveTempData($data);
      }
      $retval->retcode = TRUE;
      break;
  }

  return $retval;

}

/* Batch function called to publish article as final workflow task */
function maestro_publishArticle($queue_id, $process_id) {
  $nid = maestro_getNodeId($process_id,'article');
  if ($nid > 0) {
    $node = node_load($nid);
    node_publish_action($node);
    node_save($node);
    drupal_set_message('New article has been published');
    return TRUE;
  } else {
    return FALSE;
  }
}

?>